name : Deploying a express.js application

on :
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy Via SSH
        uses: appleboy/ssh-action@v0.1.3
        with :
          host : ${{ secrets.SSH_SECRET}}
          username : root
          key : ${{ secrets.SSH_KEY }}
          script :
            cd /home/ubuntu/Github-actions
            git pull
            docker compose up -d --build